/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsJsonRouteImport } from './routes/components-json'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ThemingRouteImport } from './routes/theming'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsAppLayoutRouteImport } from './routes/components/app-layout'
import { Route as ComponentsChoiceCardRouteImport } from './routes/components/choice-card'
import { Route as ComponentsCommandRouteImport } from './routes/components/command'
import { Route as ComponentsConfirmationModalRouteImport } from './routes/components/confirmation-modal'
import { Route as ComponentsCopyButtonRouteImport } from './routes/components/copy-button'
import { Route as ComponentsCustomerCardRouteImport } from './routes/components/customer-card'
import { Route as ComponentsDataListRouteImport } from './routes/components/data-list'
import { Route as ComponentsDataTableRouteImport } from './routes/components/data-table'
import { Route as ComponentsDatePickerRouteImport } from './routes/components/date-picker'
import { Route as ComponentsDetailCardRouteImport } from './routes/components/detail-card'
import { Route as ComponentsEmptyRouteImport } from './routes/components/empty'
import { Route as ComponentsFormBuilderRouteImport } from './routes/components/form-builder'
import { Route as ComponentsFormLayoutRouteImport } from './routes/components/form-layout'
import { Route as ComponentsMetricCardRouteImport } from './routes/components/metric-card'
import { Route as ComponentsPageLayoutRouteImport } from './routes/components/page-layout'
import { Route as ComponentsQuantityInputRouteImport } from './routes/components/quantity-input'
import { Route as ComponentsResourceListRouteImport } from './routes/components/resource-list'
import { Route as ComponentsResourcePickerRouteImport } from './routes/components/resource-picker'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsTextEditorRouteImport } from './routes/components/text-editor'
import { Route as UiIndexRouteImport } from './routes/ui/index'
import { Route as UiAvatarRouteImport } from './routes/ui/avatar'
import { Route as UiBadgeRouteImport } from './routes/ui/badge'
import { Route as UiBannerRouteImport } from './routes/ui/banner'
import { Route as UiButtonRouteImport } from './routes/ui/button'
import { Route as UiButtonGroupRouteImport } from './routes/ui/button-group'
import { Route as UiCheckboxRouteImport } from './routes/ui/checkbox'
import { Route as UiDialogRouteImport } from './routes/ui/dialog'
import { Route as UiDrawerRouteImport } from './routes/ui/drawer'
import { Route as UiDropdownMenuRouteImport } from './routes/ui/dropdown-menu'
import { Route as UiFieldRouteImport } from './routes/ui/field'
import { Route as UiFileUploadRouteImport } from './routes/ui/file-upload'
import { Route as UiFormSectionRouteImport } from './routes/ui/form-section'
import { Route as UiInputRouteImport } from './routes/ui/input'
import { Route as UiInputGroupRouteImport } from './routes/ui/input-group'
import { Route as UiLabelRouteImport } from './routes/ui/label'
import { Route as UiPaginationRouteImport } from './routes/ui/pagination'
import { Route as UiRadioGroupRouteImport } from './routes/ui/radio-group'
import { Route as UiSkeletonRouteImport } from './routes/ui/skeleton'
import { Route as UiSliderRouteImport } from './routes/ui/slider'
import { Route as UiSpinnerRouteImport } from './routes/ui/spinner'
import { Route as UiSwitchRouteImport } from './routes/ui/switch'
import { Route as UiTabsRouteImport } from './routes/ui/tabs'
import { Route as UiTextareaRouteImport } from './routes/ui/textarea'
import { Route as UiToastRouteImport } from './routes/ui/toast'
import { Route as UiTooltipRouteImport } from './routes/ui/tooltip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsJsonRoute = ComponentsJsonRouteImport.update({
  id: '/components-json',
  path: '/components-json',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemingRoute = ThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAppLayoutRoute = ComponentsAppLayoutRouteImport.update({
  id: '/components/app-layout',
  path: '/components/app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChoiceCardRoute = ComponentsChoiceCardRouteImport.update({
  id: '/components/choice-card',
  path: '/components/choice-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCommandRoute = ComponentsCommandRouteImport.update({
  id: '/components/command',
  path: '/components/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsConfirmationModalRoute =
  ComponentsConfirmationModalRouteImport.update({
    id: '/components/confirmation-modal',
    path: '/components/confirmation-modal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsCopyButtonRoute = ComponentsCopyButtonRouteImport.update({
  id: '/components/copy-button',
  path: '/components/copy-button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCustomerCardRoute = ComponentsCustomerCardRouteImport.update({
  id: '/components/customer-card',
  path: '/components/customer-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataListRoute = ComponentsDataListRouteImport.update({
  id: '/components/data-list',
  path: '/components/data-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataTableRoute = ComponentsDataTableRouteImport.update({
  id: '/components/data-table',
  path: '/components/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDatePickerRoute = ComponentsDatePickerRouteImport.update({
  id: '/components/date-picker',
  path: '/components/date-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDetailCardRoute = ComponentsDetailCardRouteImport.update({
  id: '/components/detail-card',
  path: '/components/detail-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsEmptyRoute = ComponentsEmptyRouteImport.update({
  id: '/components/empty',
  path: '/components/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormBuilderRoute = ComponentsFormBuilderRouteImport.update({
  id: '/components/form-builder',
  path: '/components/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormLayoutRoute = ComponentsFormLayoutRouteImport.update({
  id: '/components/form-layout',
  path: '/components/form-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsMetricCardRoute = ComponentsMetricCardRouteImport.update({
  id: '/components/metric-card',
  path: '/components/metric-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPageLayoutRoute = ComponentsPageLayoutRouteImport.update({
  id: '/components/page-layout',
  path: '/components/page-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsQuantityInputRoute = ComponentsQuantityInputRouteImport.update({
  id: '/components/quantity-input',
  path: '/components/quantity-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsResourceListRoute = ComponentsResourceListRouteImport.update({
  id: '/components/resource-list',
  path: '/components/resource-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsResourcePickerRoute =
  ComponentsResourcePickerRouteImport.update({
    id: '/components/resource-picker',
    path: '/components/resource-picker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextEditorRoute = ComponentsTextEditorRouteImport.update({
  id: '/components/text-editor',
  path: '/components/text-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const UiIndexRoute = UiIndexRouteImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiAvatarRoute = UiAvatarRouteImport.update({
  id: '/ui/avatar',
  path: '/ui/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const UiBadgeRoute = UiBadgeRouteImport.update({
  id: '/ui/badge',
  path: '/ui/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const UiBannerRoute = UiBannerRouteImport.update({
  id: '/ui/banner',
  path: '/ui/banner',
  getParentRoute: () => rootRouteImport,
} as any)
const UiButtonRoute = UiButtonRouteImport.update({
  id: '/ui/button',
  path: '/ui/button',
  getParentRoute: () => rootRouteImport,
} as any)
const UiButtonGroupRoute = UiButtonGroupRouteImport.update({
  id: '/ui/button-group',
  path: '/ui/button-group',
  getParentRoute: () => rootRouteImport,
} as any)
const UiCheckboxRoute = UiCheckboxRouteImport.update({
  id: '/ui/checkbox',
  path: '/ui/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDialogRoute = UiDialogRouteImport.update({
  id: '/ui/dialog',
  path: '/ui/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDrawerRoute = UiDrawerRouteImport.update({
  id: '/ui/drawer',
  path: '/ui/drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const UiDropdownMenuRoute = UiDropdownMenuRouteImport.update({
  id: '/ui/dropdown-menu',
  path: '/ui/dropdown-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const UiFieldRoute = UiFieldRouteImport.update({
  id: '/ui/field',
  path: '/ui/field',
  getParentRoute: () => rootRouteImport,
} as any)
const UiFileUploadRoute = UiFileUploadRouteImport.update({
  id: '/ui/file-upload',
  path: '/ui/file-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UiFormSectionRoute = UiFormSectionRouteImport.update({
  id: '/ui/form-section',
  path: '/ui/form-section',
  getParentRoute: () => rootRouteImport,
} as any)
const UiInputRoute = UiInputRouteImport.update({
  id: '/ui/input',
  path: '/ui/input',
  getParentRoute: () => rootRouteImport,
} as any)
const UiInputGroupRoute = UiInputGroupRouteImport.update({
  id: '/ui/input-group',
  path: '/ui/input-group',
  getParentRoute: () => rootRouteImport,
} as any)
const UiLabelRoute = UiLabelRouteImport.update({
  id: '/ui/label',
  path: '/ui/label',
  getParentRoute: () => rootRouteImport,
} as any)
const UiPaginationRoute = UiPaginationRouteImport.update({
  id: '/ui/pagination',
  path: '/ui/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRadioGroupRoute = UiRadioGroupRouteImport.update({
  id: '/ui/radio-group',
  path: '/ui/radio-group',
  getParentRoute: () => rootRouteImport,
} as any)
const UiSkeletonRoute = UiSkeletonRouteImport.update({
  id: '/ui/skeleton',
  path: '/ui/skeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const UiSliderRoute = UiSliderRouteImport.update({
  id: '/ui/slider',
  path: '/ui/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const UiSpinnerRoute = UiSpinnerRouteImport.update({
  id: '/ui/spinner',
  path: '/ui/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const UiSwitchRoute = UiSwitchRouteImport.update({
  id: '/ui/switch',
  path: '/ui/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const UiTabsRoute = UiTabsRouteImport.update({
  id: '/ui/tabs',
  path: '/ui/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const UiTextareaRoute = UiTextareaRouteImport.update({
  id: '/ui/textarea',
  path: '/ui/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const UiToastRoute = UiToastRouteImport.update({
  id: '/ui/toast',
  path: '/ui/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const UiTooltipRoute = UiTooltipRouteImport.update({
  id: '/ui/tooltip',
  path: '/ui/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components-json': typeof ComponentsJsonRoute
  '/installation': typeof InstallationRoute
  '/setup': typeof SetupRoute
  '/theming': typeof ThemingRoute
  '/components/app-layout': typeof ComponentsAppLayoutRoute
  '/components/choice-card': typeof ComponentsChoiceCardRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/confirmation-modal': typeof ComponentsConfirmationModalRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/customer-card': typeof ComponentsCustomerCardRoute
  '/components/data-list': typeof ComponentsDataListRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/detail-card': typeof ComponentsDetailCardRoute
  '/components/empty': typeof ComponentsEmptyRoute
  '/components/form-builder': typeof ComponentsFormBuilderRoute
  '/components/form-layout': typeof ComponentsFormLayoutRoute
  '/components/metric-card': typeof ComponentsMetricCardRoute
  '/components/page-layout': typeof ComponentsPageLayoutRoute
  '/components/quantity-input': typeof ComponentsQuantityInputRoute
  '/components/resource-list': typeof ComponentsResourceListRoute
  '/components/resource-picker': typeof ComponentsResourcePickerRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/text-editor': typeof ComponentsTextEditorRoute
  '/ui/avatar': typeof UiAvatarRoute
  '/ui/badge': typeof UiBadgeRoute
  '/ui/banner': typeof UiBannerRoute
  '/ui/button': typeof UiButtonRoute
  '/ui/button-group': typeof UiButtonGroupRoute
  '/ui/checkbox': typeof UiCheckboxRoute
  '/ui/dialog': typeof UiDialogRoute
  '/ui/drawer': typeof UiDrawerRoute
  '/ui/dropdown-menu': typeof UiDropdownMenuRoute
  '/ui/field': typeof UiFieldRoute
  '/ui/file-upload': typeof UiFileUploadRoute
  '/ui/form-section': typeof UiFormSectionRoute
  '/ui/input': typeof UiInputRoute
  '/ui/input-group': typeof UiInputGroupRoute
  '/ui/label': typeof UiLabelRoute
  '/ui/pagination': typeof UiPaginationRoute
  '/ui/radio-group': typeof UiRadioGroupRoute
  '/ui/skeleton': typeof UiSkeletonRoute
  '/ui/slider': typeof UiSliderRoute
  '/ui/spinner': typeof UiSpinnerRoute
  '/ui/switch': typeof UiSwitchRoute
  '/ui/tabs': typeof UiTabsRoute
  '/ui/textarea': typeof UiTextareaRoute
  '/ui/toast': typeof UiToastRoute
  '/ui/tooltip': typeof UiTooltipRoute
  '/components/': typeof ComponentsIndexRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components-json': typeof ComponentsJsonRoute
  '/installation': typeof InstallationRoute
  '/setup': typeof SetupRoute
  '/theming': typeof ThemingRoute
  '/components/app-layout': typeof ComponentsAppLayoutRoute
  '/components/choice-card': typeof ComponentsChoiceCardRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/confirmation-modal': typeof ComponentsConfirmationModalRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/customer-card': typeof ComponentsCustomerCardRoute
  '/components/data-list': typeof ComponentsDataListRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/detail-card': typeof ComponentsDetailCardRoute
  '/components/empty': typeof ComponentsEmptyRoute
  '/components/form-builder': typeof ComponentsFormBuilderRoute
  '/components/form-layout': typeof ComponentsFormLayoutRoute
  '/components/metric-card': typeof ComponentsMetricCardRoute
  '/components/page-layout': typeof ComponentsPageLayoutRoute
  '/components/quantity-input': typeof ComponentsQuantityInputRoute
  '/components/resource-list': typeof ComponentsResourceListRoute
  '/components/resource-picker': typeof ComponentsResourcePickerRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/text-editor': typeof ComponentsTextEditorRoute
  '/ui/avatar': typeof UiAvatarRoute
  '/ui/badge': typeof UiBadgeRoute
  '/ui/banner': typeof UiBannerRoute
  '/ui/button': typeof UiButtonRoute
  '/ui/button-group': typeof UiButtonGroupRoute
  '/ui/checkbox': typeof UiCheckboxRoute
  '/ui/dialog': typeof UiDialogRoute
  '/ui/drawer': typeof UiDrawerRoute
  '/ui/dropdown-menu': typeof UiDropdownMenuRoute
  '/ui/field': typeof UiFieldRoute
  '/ui/file-upload': typeof UiFileUploadRoute
  '/ui/form-section': typeof UiFormSectionRoute
  '/ui/input': typeof UiInputRoute
  '/ui/input-group': typeof UiInputGroupRoute
  '/ui/label': typeof UiLabelRoute
  '/ui/pagination': typeof UiPaginationRoute
  '/ui/radio-group': typeof UiRadioGroupRoute
  '/ui/skeleton': typeof UiSkeletonRoute
  '/ui/slider': typeof UiSliderRoute
  '/ui/spinner': typeof UiSpinnerRoute
  '/ui/switch': typeof UiSwitchRoute
  '/ui/tabs': typeof UiTabsRoute
  '/ui/textarea': typeof UiTextareaRoute
  '/ui/toast': typeof UiToastRoute
  '/ui/tooltip': typeof UiTooltipRoute
  '/components': typeof ComponentsIndexRoute
  '/ui': typeof UiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components-json': typeof ComponentsJsonRoute
  '/installation': typeof InstallationRoute
  '/setup': typeof SetupRoute
  '/theming': typeof ThemingRoute
  '/components/app-layout': typeof ComponentsAppLayoutRoute
  '/components/choice-card': typeof ComponentsChoiceCardRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/confirmation-modal': typeof ComponentsConfirmationModalRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/customer-card': typeof ComponentsCustomerCardRoute
  '/components/data-list': typeof ComponentsDataListRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/detail-card': typeof ComponentsDetailCardRoute
  '/components/empty': typeof ComponentsEmptyRoute
  '/components/form-builder': typeof ComponentsFormBuilderRoute
  '/components/form-layout': typeof ComponentsFormLayoutRoute
  '/components/metric-card': typeof ComponentsMetricCardRoute
  '/components/page-layout': typeof ComponentsPageLayoutRoute
  '/components/quantity-input': typeof ComponentsQuantityInputRoute
  '/components/resource-list': typeof ComponentsResourceListRoute
  '/components/resource-picker': typeof ComponentsResourcePickerRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/text-editor': typeof ComponentsTextEditorRoute
  '/ui/avatar': typeof UiAvatarRoute
  '/ui/badge': typeof UiBadgeRoute
  '/ui/banner': typeof UiBannerRoute
  '/ui/button': typeof UiButtonRoute
  '/ui/button-group': typeof UiButtonGroupRoute
  '/ui/checkbox': typeof UiCheckboxRoute
  '/ui/dialog': typeof UiDialogRoute
  '/ui/drawer': typeof UiDrawerRoute
  '/ui/dropdown-menu': typeof UiDropdownMenuRoute
  '/ui/field': typeof UiFieldRoute
  '/ui/file-upload': typeof UiFileUploadRoute
  '/ui/form-section': typeof UiFormSectionRoute
  '/ui/input': typeof UiInputRoute
  '/ui/input-group': typeof UiInputGroupRoute
  '/ui/label': typeof UiLabelRoute
  '/ui/pagination': typeof UiPaginationRoute
  '/ui/radio-group': typeof UiRadioGroupRoute
  '/ui/skeleton': typeof UiSkeletonRoute
  '/ui/slider': typeof UiSliderRoute
  '/ui/spinner': typeof UiSpinnerRoute
  '/ui/switch': typeof UiSwitchRoute
  '/ui/tabs': typeof UiTabsRoute
  '/ui/textarea': typeof UiTextareaRoute
  '/ui/toast': typeof UiToastRoute
  '/ui/tooltip': typeof UiTooltipRoute
  '/components/': typeof ComponentsIndexRoute
  '/ui/': typeof UiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components-json'
    | '/installation'
    | '/setup'
    | '/theming'
    | '/components/app-layout'
    | '/components/choice-card'
    | '/components/command'
    | '/components/confirmation-modal'
    | '/components/copy-button'
    | '/components/customer-card'
    | '/components/data-list'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/detail-card'
    | '/components/empty'
    | '/components/form-builder'
    | '/components/form-layout'
    | '/components/metric-card'
    | '/components/page-layout'
    | '/components/quantity-input'
    | '/components/resource-list'
    | '/components/resource-picker'
    | '/components/select'
    | '/components/text-editor'
    | '/ui/avatar'
    | '/ui/badge'
    | '/ui/banner'
    | '/ui/button'
    | '/ui/button-group'
    | '/ui/checkbox'
    | '/ui/dialog'
    | '/ui/drawer'
    | '/ui/dropdown-menu'
    | '/ui/field'
    | '/ui/file-upload'
    | '/ui/form-section'
    | '/ui/input'
    | '/ui/input-group'
    | '/ui/label'
    | '/ui/pagination'
    | '/ui/radio-group'
    | '/ui/skeleton'
    | '/ui/slider'
    | '/ui/spinner'
    | '/ui/switch'
    | '/ui/tabs'
    | '/ui/textarea'
    | '/ui/toast'
    | '/ui/tooltip'
    | '/components/'
    | '/ui/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components-json'
    | '/installation'
    | '/setup'
    | '/theming'
    | '/components/app-layout'
    | '/components/choice-card'
    | '/components/command'
    | '/components/confirmation-modal'
    | '/components/copy-button'
    | '/components/customer-card'
    | '/components/data-list'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/detail-card'
    | '/components/empty'
    | '/components/form-builder'
    | '/components/form-layout'
    | '/components/metric-card'
    | '/components/page-layout'
    | '/components/quantity-input'
    | '/components/resource-list'
    | '/components/resource-picker'
    | '/components/select'
    | '/components/text-editor'
    | '/ui/avatar'
    | '/ui/badge'
    | '/ui/banner'
    | '/ui/button'
    | '/ui/button-group'
    | '/ui/checkbox'
    | '/ui/dialog'
    | '/ui/drawer'
    | '/ui/dropdown-menu'
    | '/ui/field'
    | '/ui/file-upload'
    | '/ui/form-section'
    | '/ui/input'
    | '/ui/input-group'
    | '/ui/label'
    | '/ui/pagination'
    | '/ui/radio-group'
    | '/ui/skeleton'
    | '/ui/slider'
    | '/ui/spinner'
    | '/ui/switch'
    | '/ui/tabs'
    | '/ui/textarea'
    | '/ui/toast'
    | '/ui/tooltip'
    | '/components'
    | '/ui'
  id:
    | '__root__'
    | '/'
    | '/components-json'
    | '/installation'
    | '/setup'
    | '/theming'
    | '/components/app-layout'
    | '/components/choice-card'
    | '/components/command'
    | '/components/confirmation-modal'
    | '/components/copy-button'
    | '/components/customer-card'
    | '/components/data-list'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/detail-card'
    | '/components/empty'
    | '/components/form-builder'
    | '/components/form-layout'
    | '/components/metric-card'
    | '/components/page-layout'
    | '/components/quantity-input'
    | '/components/resource-list'
    | '/components/resource-picker'
    | '/components/select'
    | '/components/text-editor'
    | '/ui/avatar'
    | '/ui/badge'
    | '/ui/banner'
    | '/ui/button'
    | '/ui/button-group'
    | '/ui/checkbox'
    | '/ui/dialog'
    | '/ui/drawer'
    | '/ui/dropdown-menu'
    | '/ui/field'
    | '/ui/file-upload'
    | '/ui/form-section'
    | '/ui/input'
    | '/ui/input-group'
    | '/ui/label'
    | '/ui/pagination'
    | '/ui/radio-group'
    | '/ui/skeleton'
    | '/ui/slider'
    | '/ui/spinner'
    | '/ui/switch'
    | '/ui/tabs'
    | '/ui/textarea'
    | '/ui/toast'
    | '/ui/tooltip'
    | '/components/'
    | '/ui/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsJsonRoute: typeof ComponentsJsonRoute
  InstallationRoute: typeof InstallationRoute
  SetupRoute: typeof SetupRoute
  ThemingRoute: typeof ThemingRoute
  ComponentsAppLayoutRoute: typeof ComponentsAppLayoutRoute
  ComponentsChoiceCardRoute: typeof ComponentsChoiceCardRoute
  ComponentsCommandRoute: typeof ComponentsCommandRoute
  ComponentsConfirmationModalRoute: typeof ComponentsConfirmationModalRoute
  ComponentsCopyButtonRoute: typeof ComponentsCopyButtonRoute
  ComponentsCustomerCardRoute: typeof ComponentsCustomerCardRoute
  ComponentsDataListRoute: typeof ComponentsDataListRoute
  ComponentsDataTableRoute: typeof ComponentsDataTableRoute
  ComponentsDatePickerRoute: typeof ComponentsDatePickerRoute
  ComponentsDetailCardRoute: typeof ComponentsDetailCardRoute
  ComponentsEmptyRoute: typeof ComponentsEmptyRoute
  ComponentsFormBuilderRoute: typeof ComponentsFormBuilderRoute
  ComponentsFormLayoutRoute: typeof ComponentsFormLayoutRoute
  ComponentsMetricCardRoute: typeof ComponentsMetricCardRoute
  ComponentsPageLayoutRoute: typeof ComponentsPageLayoutRoute
  ComponentsQuantityInputRoute: typeof ComponentsQuantityInputRoute
  ComponentsResourceListRoute: typeof ComponentsResourceListRoute
  ComponentsResourcePickerRoute: typeof ComponentsResourcePickerRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsTextEditorRoute: typeof ComponentsTextEditorRoute
  UiAvatarRoute: typeof UiAvatarRoute
  UiBadgeRoute: typeof UiBadgeRoute
  UiBannerRoute: typeof UiBannerRoute
  UiButtonRoute: typeof UiButtonRoute
  UiButtonGroupRoute: typeof UiButtonGroupRoute
  UiCheckboxRoute: typeof UiCheckboxRoute
  UiDialogRoute: typeof UiDialogRoute
  UiDrawerRoute: typeof UiDrawerRoute
  UiDropdownMenuRoute: typeof UiDropdownMenuRoute
  UiFieldRoute: typeof UiFieldRoute
  UiFileUploadRoute: typeof UiFileUploadRoute
  UiFormSectionRoute: typeof UiFormSectionRoute
  UiInputRoute: typeof UiInputRoute
  UiInputGroupRoute: typeof UiInputGroupRoute
  UiLabelRoute: typeof UiLabelRoute
  UiPaginationRoute: typeof UiPaginationRoute
  UiRadioGroupRoute: typeof UiRadioGroupRoute
  UiSkeletonRoute: typeof UiSkeletonRoute
  UiSliderRoute: typeof UiSliderRoute
  UiSpinnerRoute: typeof UiSpinnerRoute
  UiSwitchRoute: typeof UiSwitchRoute
  UiTabsRoute: typeof UiTabsRoute
  UiTextareaRoute: typeof UiTextareaRoute
  UiToastRoute: typeof UiToastRoute
  UiTooltipRoute: typeof UiTooltipRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  UiIndexRoute: typeof UiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components-json': {
      id: '/components-json'
      path: '/components-json'
      fullPath: '/components-json'
      preLoaderRoute: typeof ComponentsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theming': {
      id: '/theming'
      path: '/theming'
      fullPath: '/theming'
      preLoaderRoute: typeof ThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/app-layout': {
      id: '/components/app-layout'
      path: '/components/app-layout'
      fullPath: '/components/app-layout'
      preLoaderRoute: typeof ComponentsAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/choice-card': {
      id: '/components/choice-card'
      path: '/components/choice-card'
      fullPath: '/components/choice-card'
      preLoaderRoute: typeof ComponentsChoiceCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/command': {
      id: '/components/command'
      path: '/components/command'
      fullPath: '/components/command'
      preLoaderRoute: typeof ComponentsCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/confirmation-modal': {
      id: '/components/confirmation-modal'
      path: '/components/confirmation-modal'
      fullPath: '/components/confirmation-modal'
      preLoaderRoute: typeof ComponentsConfirmationModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/copy-button': {
      id: '/components/copy-button'
      path: '/components/copy-button'
      fullPath: '/components/copy-button'
      preLoaderRoute: typeof ComponentsCopyButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/customer-card': {
      id: '/components/customer-card'
      path: '/components/customer-card'
      fullPath: '/components/customer-card'
      preLoaderRoute: typeof ComponentsCustomerCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-list': {
      id: '/components/data-list'
      path: '/components/data-list'
      fullPath: '/components/data-list'
      preLoaderRoute: typeof ComponentsDataListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-table': {
      id: '/components/data-table'
      path: '/components/data-table'
      fullPath: '/components/data-table'
      preLoaderRoute: typeof ComponentsDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/date-picker': {
      id: '/components/date-picker'
      path: '/components/date-picker'
      fullPath: '/components/date-picker'
      preLoaderRoute: typeof ComponentsDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/detail-card': {
      id: '/components/detail-card'
      path: '/components/detail-card'
      fullPath: '/components/detail-card'
      preLoaderRoute: typeof ComponentsDetailCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/empty': {
      id: '/components/empty'
      path: '/components/empty'
      fullPath: '/components/empty'
      preLoaderRoute: typeof ComponentsEmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/form-builder': {
      id: '/components/form-builder'
      path: '/components/form-builder'
      fullPath: '/components/form-builder'
      preLoaderRoute: typeof ComponentsFormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/form-layout': {
      id: '/components/form-layout'
      path: '/components/form-layout'
      fullPath: '/components/form-layout'
      preLoaderRoute: typeof ComponentsFormLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/metric-card': {
      id: '/components/metric-card'
      path: '/components/metric-card'
      fullPath: '/components/metric-card'
      preLoaderRoute: typeof ComponentsMetricCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/page-layout': {
      id: '/components/page-layout'
      path: '/components/page-layout'
      fullPath: '/components/page-layout'
      preLoaderRoute: typeof ComponentsPageLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/quantity-input': {
      id: '/components/quantity-input'
      path: '/components/quantity-input'
      fullPath: '/components/quantity-input'
      preLoaderRoute: typeof ComponentsQuantityInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/resource-list': {
      id: '/components/resource-list'
      path: '/components/resource-list'
      fullPath: '/components/resource-list'
      preLoaderRoute: typeof ComponentsResourceListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/resource-picker': {
      id: '/components/resource-picker'
      path: '/components/resource-picker'
      fullPath: '/components/resource-picker'
      preLoaderRoute: typeof ComponentsResourcePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/text-editor': {
      id: '/components/text-editor'
      path: '/components/text-editor'
      fullPath: '/components/text-editor'
      preLoaderRoute: typeof ComponentsTextEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/': {
      id: '/ui/'
      path: '/ui'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/avatar': {
      id: '/ui/avatar'
      path: '/ui/avatar'
      fullPath: '/ui/avatar'
      preLoaderRoute: typeof UiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/badge': {
      id: '/ui/badge'
      path: '/ui/badge'
      fullPath: '/ui/badge'
      preLoaderRoute: typeof UiBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/banner': {
      id: '/ui/banner'
      path: '/ui/banner'
      fullPath: '/ui/banner'
      preLoaderRoute: typeof UiBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/button': {
      id: '/ui/button'
      path: '/ui/button'
      fullPath: '/ui/button'
      preLoaderRoute: typeof UiButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/button-group': {
      id: '/ui/button-group'
      path: '/ui/button-group'
      fullPath: '/ui/button-group'
      preLoaderRoute: typeof UiButtonGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/checkbox': {
      id: '/ui/checkbox'
      path: '/ui/checkbox'
      fullPath: '/ui/checkbox'
      preLoaderRoute: typeof UiCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/dialog': {
      id: '/ui/dialog'
      path: '/ui/dialog'
      fullPath: '/ui/dialog'
      preLoaderRoute: typeof UiDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/drawer': {
      id: '/ui/drawer'
      path: '/ui/drawer'
      fullPath: '/ui/drawer'
      preLoaderRoute: typeof UiDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/dropdown-menu': {
      id: '/ui/dropdown-menu'
      path: '/ui/dropdown-menu'
      fullPath: '/ui/dropdown-menu'
      preLoaderRoute: typeof UiDropdownMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/field': {
      id: '/ui/field'
      path: '/ui/field'
      fullPath: '/ui/field'
      preLoaderRoute: typeof UiFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/file-upload': {
      id: '/ui/file-upload'
      path: '/ui/file-upload'
      fullPath: '/ui/file-upload'
      preLoaderRoute: typeof UiFileUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/form-section': {
      id: '/ui/form-section'
      path: '/ui/form-section'
      fullPath: '/ui/form-section'
      preLoaderRoute: typeof UiFormSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/input': {
      id: '/ui/input'
      path: '/ui/input'
      fullPath: '/ui/input'
      preLoaderRoute: typeof UiInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/input-group': {
      id: '/ui/input-group'
      path: '/ui/input-group'
      fullPath: '/ui/input-group'
      preLoaderRoute: typeof UiInputGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/label': {
      id: '/ui/label'
      path: '/ui/label'
      fullPath: '/ui/label'
      preLoaderRoute: typeof UiLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/pagination': {
      id: '/ui/pagination'
      path: '/ui/pagination'
      fullPath: '/ui/pagination'
      preLoaderRoute: typeof UiPaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/radio-group': {
      id: '/ui/radio-group'
      path: '/ui/radio-group'
      fullPath: '/ui/radio-group'
      preLoaderRoute: typeof UiRadioGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/skeleton': {
      id: '/ui/skeleton'
      path: '/ui/skeleton'
      fullPath: '/ui/skeleton'
      preLoaderRoute: typeof UiSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/slider': {
      id: '/ui/slider'
      path: '/ui/slider'
      fullPath: '/ui/slider'
      preLoaderRoute: typeof UiSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/spinner': {
      id: '/ui/spinner'
      path: '/ui/spinner'
      fullPath: '/ui/spinner'
      preLoaderRoute: typeof UiSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/switch': {
      id: '/ui/switch'
      path: '/ui/switch'
      fullPath: '/ui/switch'
      preLoaderRoute: typeof UiSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/tabs': {
      id: '/ui/tabs'
      path: '/ui/tabs'
      fullPath: '/ui/tabs'
      preLoaderRoute: typeof UiTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/textarea': {
      id: '/ui/textarea'
      path: '/ui/textarea'
      fullPath: '/ui/textarea'
      preLoaderRoute: typeof UiTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/toast': {
      id: '/ui/toast'
      path: '/ui/toast'
      fullPath: '/ui/toast'
      preLoaderRoute: typeof UiToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/tooltip': {
      id: '/ui/tooltip'
      path: '/ui/tooltip'
      fullPath: '/ui/tooltip'
      preLoaderRoute: typeof UiTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsJsonRoute: ComponentsJsonRoute,
  InstallationRoute: InstallationRoute,
  SetupRoute: SetupRoute,
  ThemingRoute: ThemingRoute,
  ComponentsAppLayoutRoute: ComponentsAppLayoutRoute,
  ComponentsChoiceCardRoute: ComponentsChoiceCardRoute,
  ComponentsCommandRoute: ComponentsCommandRoute,
  ComponentsConfirmationModalRoute: ComponentsConfirmationModalRoute,
  ComponentsCopyButtonRoute: ComponentsCopyButtonRoute,
  ComponentsCustomerCardRoute: ComponentsCustomerCardRoute,
  ComponentsDataListRoute: ComponentsDataListRoute,
  ComponentsDataTableRoute: ComponentsDataTableRoute,
  ComponentsDatePickerRoute: ComponentsDatePickerRoute,
  ComponentsDetailCardRoute: ComponentsDetailCardRoute,
  ComponentsEmptyRoute: ComponentsEmptyRoute,
  ComponentsFormBuilderRoute: ComponentsFormBuilderRoute,
  ComponentsFormLayoutRoute: ComponentsFormLayoutRoute,
  ComponentsMetricCardRoute: ComponentsMetricCardRoute,
  ComponentsPageLayoutRoute: ComponentsPageLayoutRoute,
  ComponentsQuantityInputRoute: ComponentsQuantityInputRoute,
  ComponentsResourceListRoute: ComponentsResourceListRoute,
  ComponentsResourcePickerRoute: ComponentsResourcePickerRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsTextEditorRoute: ComponentsTextEditorRoute,
  UiAvatarRoute: UiAvatarRoute,
  UiBadgeRoute: UiBadgeRoute,
  UiBannerRoute: UiBannerRoute,
  UiButtonRoute: UiButtonRoute,
  UiButtonGroupRoute: UiButtonGroupRoute,
  UiCheckboxRoute: UiCheckboxRoute,
  UiDialogRoute: UiDialogRoute,
  UiDrawerRoute: UiDrawerRoute,
  UiDropdownMenuRoute: UiDropdownMenuRoute,
  UiFieldRoute: UiFieldRoute,
  UiFileUploadRoute: UiFileUploadRoute,
  UiFormSectionRoute: UiFormSectionRoute,
  UiInputRoute: UiInputRoute,
  UiInputGroupRoute: UiInputGroupRoute,
  UiLabelRoute: UiLabelRoute,
  UiPaginationRoute: UiPaginationRoute,
  UiRadioGroupRoute: UiRadioGroupRoute,
  UiSkeletonRoute: UiSkeletonRoute,
  UiSliderRoute: UiSliderRoute,
  UiSpinnerRoute: UiSpinnerRoute,
  UiSwitchRoute: UiSwitchRoute,
  UiTabsRoute: UiTabsRoute,
  UiTextareaRoute: UiTextareaRoute,
  UiToastRoute: UiToastRoute,
  UiTooltipRoute: UiTooltipRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  UiIndexRoute: UiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
