/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsJsonRouteImport } from './routes/components-json'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ThemingRouteImport } from './routes/theming'
import { Route as BaseUiIndexRouteImport } from './routes/base-ui/index'
import { Route as BaseUiAccordionRouteImport } from './routes/base-ui/accordion'
import { Route as BaseUiAspectRatioRouteImport } from './routes/base-ui/aspect-ratio'
import { Route as BaseUiAvatarRouteImport } from './routes/base-ui/avatar'
import { Route as BaseUiBadgeRouteImport } from './routes/base-ui/badge'
import { Route as BaseUiBannerRouteImport } from './routes/base-ui/banner'
import { Route as BaseUiButtonRouteImport } from './routes/base-ui/button'
import { Route as BaseUiButtonGroupRouteImport } from './routes/base-ui/button-group'
import { Route as BaseUiChartRouteImport } from './routes/base-ui/chart'
import { Route as BaseUiCheckboxRouteImport } from './routes/base-ui/checkbox'
import { Route as BaseUiCollapsibleRouteImport } from './routes/base-ui/collapsible'
import { Route as BaseUiDialogRouteImport } from './routes/base-ui/dialog'
import { Route as BaseUiDrawerRouteImport } from './routes/base-ui/drawer'
import { Route as BaseUiDropdownMenuRouteImport } from './routes/base-ui/dropdown-menu'
import { Route as BaseUiFieldRouteImport } from './routes/base-ui/field'
import { Route as BaseUiFileUploadRouteImport } from './routes/base-ui/file-upload'
import { Route as BaseUiFormSectionRouteImport } from './routes/base-ui/form-section'
import { Route as BaseUiInputRouteImport } from './routes/base-ui/input'
import { Route as BaseUiInputGroupRouteImport } from './routes/base-ui/input-group'
import { Route as BaseUiKbdRouteImport } from './routes/base-ui/kbd'
import { Route as BaseUiLabelRouteImport } from './routes/base-ui/label'
import { Route as BaseUiPaginationRouteImport } from './routes/base-ui/pagination'
import { Route as BaseUiProgressRouteImport } from './routes/base-ui/progress'
import { Route as BaseUiRadioGroupRouteImport } from './routes/base-ui/radio-group'
import { Route as BaseUiSkeletonRouteImport } from './routes/base-ui/skeleton'
import { Route as BaseUiSliderRouteImport } from './routes/base-ui/slider'
import { Route as BaseUiSpinnerRouteImport } from './routes/base-ui/spinner'
import { Route as BaseUiSwitchRouteImport } from './routes/base-ui/switch'
import { Route as BaseUiTabsRouteImport } from './routes/base-ui/tabs'
import { Route as BaseUiTextareaRouteImport } from './routes/base-ui/textarea'
import { Route as BaseUiToastRouteImport } from './routes/base-ui/toast'
import { Route as BaseUiTooltipRouteImport } from './routes/base-ui/tooltip'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsAppLayoutRouteImport } from './routes/components/app-layout'
import { Route as ComponentsChoiceCardRouteImport } from './routes/components/choice-card'
import { Route as ComponentsCommandRouteImport } from './routes/components/command'
import { Route as ComponentsConfirmationModalRouteImport } from './routes/components/confirmation-modal'
import { Route as ComponentsCopyButtonRouteImport } from './routes/components/copy-button'
import { Route as ComponentsCustomerCardRouteImport } from './routes/components/customer-card'
import { Route as ComponentsDataListRouteImport } from './routes/components/data-list'
import { Route as ComponentsDataTableRouteImport } from './routes/components/data-table'
import { Route as ComponentsDatePickerRouteImport } from './routes/components/date-picker'
import { Route as ComponentsDetailCardRouteImport } from './routes/components/detail-card'
import { Route as ComponentsEmptyRouteImport } from './routes/components/empty'
import { Route as ComponentsFormBuilderRouteImport } from './routes/components/form-builder'
import { Route as ComponentsFormLayoutRouteImport } from './routes/components/form-layout'
import { Route as ComponentsMetricCardRouteImport } from './routes/components/metric-card'
import { Route as ComponentsPageLayoutRouteImport } from './routes/components/page-layout'
import { Route as ComponentsQuantityInputRouteImport } from './routes/components/quantity-input'
import { Route as ComponentsResourcePickerRouteImport } from './routes/components/resource-picker'
import { Route as ComponentsRoleSelectRouteImport } from './routes/components/role-select'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsSidebarRouteImport } from './routes/components/sidebar'
import { Route as ComponentsStaffSelectRouteImport } from './routes/components/staff-select'
import { Route as ComponentsTextEditorRouteImport } from './routes/components/text-editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsJsonRoute = ComponentsJsonRouteImport.update({
  id: '/components-json',
  path: '/components-json',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemingRoute = ThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiIndexRoute = BaseUiIndexRouteImport.update({
  id: '/base-ui/',
  path: '/base-ui/',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiAccordionRoute = BaseUiAccordionRouteImport.update({
  id: '/base-ui/accordion',
  path: '/base-ui/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiAspectRatioRoute = BaseUiAspectRatioRouteImport.update({
  id: '/base-ui/aspect-ratio',
  path: '/base-ui/aspect-ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiAvatarRoute = BaseUiAvatarRouteImport.update({
  id: '/base-ui/avatar',
  path: '/base-ui/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiBadgeRoute = BaseUiBadgeRouteImport.update({
  id: '/base-ui/badge',
  path: '/base-ui/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiBannerRoute = BaseUiBannerRouteImport.update({
  id: '/base-ui/banner',
  path: '/base-ui/banner',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiButtonRoute = BaseUiButtonRouteImport.update({
  id: '/base-ui/button',
  path: '/base-ui/button',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiButtonGroupRoute = BaseUiButtonGroupRouteImport.update({
  id: '/base-ui/button-group',
  path: '/base-ui/button-group',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiChartRoute = BaseUiChartRouteImport.update({
  id: '/base-ui/chart',
  path: '/base-ui/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiCheckboxRoute = BaseUiCheckboxRouteImport.update({
  id: '/base-ui/checkbox',
  path: '/base-ui/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiCollapsibleRoute = BaseUiCollapsibleRouteImport.update({
  id: '/base-ui/collapsible',
  path: '/base-ui/collapsible',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiDialogRoute = BaseUiDialogRouteImport.update({
  id: '/base-ui/dialog',
  path: '/base-ui/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiDrawerRoute = BaseUiDrawerRouteImport.update({
  id: '/base-ui/drawer',
  path: '/base-ui/drawer',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiDropdownMenuRoute = BaseUiDropdownMenuRouteImport.update({
  id: '/base-ui/dropdown-menu',
  path: '/base-ui/dropdown-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiFieldRoute = BaseUiFieldRouteImport.update({
  id: '/base-ui/field',
  path: '/base-ui/field',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiFileUploadRoute = BaseUiFileUploadRouteImport.update({
  id: '/base-ui/file-upload',
  path: '/base-ui/file-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiFormSectionRoute = BaseUiFormSectionRouteImport.update({
  id: '/base-ui/form-section',
  path: '/base-ui/form-section',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiInputRoute = BaseUiInputRouteImport.update({
  id: '/base-ui/input',
  path: '/base-ui/input',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiInputGroupRoute = BaseUiInputGroupRouteImport.update({
  id: '/base-ui/input-group',
  path: '/base-ui/input-group',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiKbdRoute = BaseUiKbdRouteImport.update({
  id: '/base-ui/kbd',
  path: '/base-ui/kbd',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiLabelRoute = BaseUiLabelRouteImport.update({
  id: '/base-ui/label',
  path: '/base-ui/label',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiPaginationRoute = BaseUiPaginationRouteImport.update({
  id: '/base-ui/pagination',
  path: '/base-ui/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiProgressRoute = BaseUiProgressRouteImport.update({
  id: '/base-ui/progress',
  path: '/base-ui/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiRadioGroupRoute = BaseUiRadioGroupRouteImport.update({
  id: '/base-ui/radio-group',
  path: '/base-ui/radio-group',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiSkeletonRoute = BaseUiSkeletonRouteImport.update({
  id: '/base-ui/skeleton',
  path: '/base-ui/skeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiSliderRoute = BaseUiSliderRouteImport.update({
  id: '/base-ui/slider',
  path: '/base-ui/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiSpinnerRoute = BaseUiSpinnerRouteImport.update({
  id: '/base-ui/spinner',
  path: '/base-ui/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiSwitchRoute = BaseUiSwitchRouteImport.update({
  id: '/base-ui/switch',
  path: '/base-ui/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiTabsRoute = BaseUiTabsRouteImport.update({
  id: '/base-ui/tabs',
  path: '/base-ui/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiTextareaRoute = BaseUiTextareaRouteImport.update({
  id: '/base-ui/textarea',
  path: '/base-ui/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiToastRoute = BaseUiToastRouteImport.update({
  id: '/base-ui/toast',
  path: '/base-ui/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseUiTooltipRoute = BaseUiTooltipRouteImport.update({
  id: '/base-ui/tooltip',
  path: '/base-ui/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAppLayoutRoute = ComponentsAppLayoutRouteImport.update({
  id: '/components/app-layout',
  path: '/components/app-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChoiceCardRoute = ComponentsChoiceCardRouteImport.update({
  id: '/components/choice-card',
  path: '/components/choice-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCommandRoute = ComponentsCommandRouteImport.update({
  id: '/components/command',
  path: '/components/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsConfirmationModalRoute =
  ComponentsConfirmationModalRouteImport.update({
    id: '/components/confirmation-modal',
    path: '/components/confirmation-modal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsCopyButtonRoute = ComponentsCopyButtonRouteImport.update({
  id: '/components/copy-button',
  path: '/components/copy-button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCustomerCardRoute = ComponentsCustomerCardRouteImport.update({
  id: '/components/customer-card',
  path: '/components/customer-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataListRoute = ComponentsDataListRouteImport.update({
  id: '/components/data-list',
  path: '/components/data-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataTableRoute = ComponentsDataTableRouteImport.update({
  id: '/components/data-table',
  path: '/components/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDatePickerRoute = ComponentsDatePickerRouteImport.update({
  id: '/components/date-picker',
  path: '/components/date-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDetailCardRoute = ComponentsDetailCardRouteImport.update({
  id: '/components/detail-card',
  path: '/components/detail-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsEmptyRoute = ComponentsEmptyRouteImport.update({
  id: '/components/empty',
  path: '/components/empty',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormBuilderRoute = ComponentsFormBuilderRouteImport.update({
  id: '/components/form-builder',
  path: '/components/form-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFormLayoutRoute = ComponentsFormLayoutRouteImport.update({
  id: '/components/form-layout',
  path: '/components/form-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsMetricCardRoute = ComponentsMetricCardRouteImport.update({
  id: '/components/metric-card',
  path: '/components/metric-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPageLayoutRoute = ComponentsPageLayoutRouteImport.update({
  id: '/components/page-layout',
  path: '/components/page-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsQuantityInputRoute = ComponentsQuantityInputRouteImport.update({
  id: '/components/quantity-input',
  path: '/components/quantity-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsResourcePickerRoute =
  ComponentsResourcePickerRouteImport.update({
    id: '/components/resource-picker',
    path: '/components/resource-picker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsRoleSelectRoute = ComponentsRoleSelectRouteImport.update({
  id: '/components/role-select',
  path: '/components/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSidebarRoute = ComponentsSidebarRouteImport.update({
  id: '/components/sidebar',
  path: '/components/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsStaffSelectRoute = ComponentsStaffSelectRouteImport.update({
  id: '/components/staff-select',
  path: '/components/staff-select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextEditorRoute = ComponentsTextEditorRouteImport.update({
  id: '/components/text-editor',
  path: '/components/text-editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components-json': typeof ComponentsJsonRoute
  '/installation': typeof InstallationRoute
  '/setup': typeof SetupRoute
  '/theming': typeof ThemingRoute
  '/base-ui/accordion': typeof BaseUiAccordionRoute
  '/base-ui/aspect-ratio': typeof BaseUiAspectRatioRoute
  '/base-ui/avatar': typeof BaseUiAvatarRoute
  '/base-ui/badge': typeof BaseUiBadgeRoute
  '/base-ui/banner': typeof BaseUiBannerRoute
  '/base-ui/button': typeof BaseUiButtonRoute
  '/base-ui/button-group': typeof BaseUiButtonGroupRoute
  '/base-ui/chart': typeof BaseUiChartRoute
  '/base-ui/checkbox': typeof BaseUiCheckboxRoute
  '/base-ui/collapsible': typeof BaseUiCollapsibleRoute
  '/base-ui/dialog': typeof BaseUiDialogRoute
  '/base-ui/drawer': typeof BaseUiDrawerRoute
  '/base-ui/dropdown-menu': typeof BaseUiDropdownMenuRoute
  '/base-ui/field': typeof BaseUiFieldRoute
  '/base-ui/file-upload': typeof BaseUiFileUploadRoute
  '/base-ui/form-section': typeof BaseUiFormSectionRoute
  '/base-ui/input': typeof BaseUiInputRoute
  '/base-ui/input-group': typeof BaseUiInputGroupRoute
  '/base-ui/kbd': typeof BaseUiKbdRoute
  '/base-ui/label': typeof BaseUiLabelRoute
  '/base-ui/pagination': typeof BaseUiPaginationRoute
  '/base-ui/progress': typeof BaseUiProgressRoute
  '/base-ui/radio-group': typeof BaseUiRadioGroupRoute
  '/base-ui/skeleton': typeof BaseUiSkeletonRoute
  '/base-ui/slider': typeof BaseUiSliderRoute
  '/base-ui/spinner': typeof BaseUiSpinnerRoute
  '/base-ui/switch': typeof BaseUiSwitchRoute
  '/base-ui/tabs': typeof BaseUiTabsRoute
  '/base-ui/textarea': typeof BaseUiTextareaRoute
  '/base-ui/toast': typeof BaseUiToastRoute
  '/base-ui/tooltip': typeof BaseUiTooltipRoute
  '/components/app-layout': typeof ComponentsAppLayoutRoute
  '/components/choice-card': typeof ComponentsChoiceCardRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/confirmation-modal': typeof ComponentsConfirmationModalRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/customer-card': typeof ComponentsCustomerCardRoute
  '/components/data-list': typeof ComponentsDataListRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/detail-card': typeof ComponentsDetailCardRoute
  '/components/empty': typeof ComponentsEmptyRoute
  '/components/form-builder': typeof ComponentsFormBuilderRoute
  '/components/form-layout': typeof ComponentsFormLayoutRoute
  '/components/metric-card': typeof ComponentsMetricCardRoute
  '/components/page-layout': typeof ComponentsPageLayoutRoute
  '/components/quantity-input': typeof ComponentsQuantityInputRoute
  '/components/resource-picker': typeof ComponentsResourcePickerRoute
  '/components/role-select': typeof ComponentsRoleSelectRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/staff-select': typeof ComponentsStaffSelectRoute
  '/components/text-editor': typeof ComponentsTextEditorRoute
  '/base-ui/': typeof BaseUiIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components-json': typeof ComponentsJsonRoute
  '/installation': typeof InstallationRoute
  '/setup': typeof SetupRoute
  '/theming': typeof ThemingRoute
  '/base-ui/accordion': typeof BaseUiAccordionRoute
  '/base-ui/aspect-ratio': typeof BaseUiAspectRatioRoute
  '/base-ui/avatar': typeof BaseUiAvatarRoute
  '/base-ui/badge': typeof BaseUiBadgeRoute
  '/base-ui/banner': typeof BaseUiBannerRoute
  '/base-ui/button': typeof BaseUiButtonRoute
  '/base-ui/button-group': typeof BaseUiButtonGroupRoute
  '/base-ui/chart': typeof BaseUiChartRoute
  '/base-ui/checkbox': typeof BaseUiCheckboxRoute
  '/base-ui/collapsible': typeof BaseUiCollapsibleRoute
  '/base-ui/dialog': typeof BaseUiDialogRoute
  '/base-ui/drawer': typeof BaseUiDrawerRoute
  '/base-ui/dropdown-menu': typeof BaseUiDropdownMenuRoute
  '/base-ui/field': typeof BaseUiFieldRoute
  '/base-ui/file-upload': typeof BaseUiFileUploadRoute
  '/base-ui/form-section': typeof BaseUiFormSectionRoute
  '/base-ui/input': typeof BaseUiInputRoute
  '/base-ui/input-group': typeof BaseUiInputGroupRoute
  '/base-ui/kbd': typeof BaseUiKbdRoute
  '/base-ui/label': typeof BaseUiLabelRoute
  '/base-ui/pagination': typeof BaseUiPaginationRoute
  '/base-ui/progress': typeof BaseUiProgressRoute
  '/base-ui/radio-group': typeof BaseUiRadioGroupRoute
  '/base-ui/skeleton': typeof BaseUiSkeletonRoute
  '/base-ui/slider': typeof BaseUiSliderRoute
  '/base-ui/spinner': typeof BaseUiSpinnerRoute
  '/base-ui/switch': typeof BaseUiSwitchRoute
  '/base-ui/tabs': typeof BaseUiTabsRoute
  '/base-ui/textarea': typeof BaseUiTextareaRoute
  '/base-ui/toast': typeof BaseUiToastRoute
  '/base-ui/tooltip': typeof BaseUiTooltipRoute
  '/components/app-layout': typeof ComponentsAppLayoutRoute
  '/components/choice-card': typeof ComponentsChoiceCardRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/confirmation-modal': typeof ComponentsConfirmationModalRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/customer-card': typeof ComponentsCustomerCardRoute
  '/components/data-list': typeof ComponentsDataListRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/detail-card': typeof ComponentsDetailCardRoute
  '/components/empty': typeof ComponentsEmptyRoute
  '/components/form-builder': typeof ComponentsFormBuilderRoute
  '/components/form-layout': typeof ComponentsFormLayoutRoute
  '/components/metric-card': typeof ComponentsMetricCardRoute
  '/components/page-layout': typeof ComponentsPageLayoutRoute
  '/components/quantity-input': typeof ComponentsQuantityInputRoute
  '/components/resource-picker': typeof ComponentsResourcePickerRoute
  '/components/role-select': typeof ComponentsRoleSelectRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/staff-select': typeof ComponentsStaffSelectRoute
  '/components/text-editor': typeof ComponentsTextEditorRoute
  '/base-ui': typeof BaseUiIndexRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components-json': typeof ComponentsJsonRoute
  '/installation': typeof InstallationRoute
  '/setup': typeof SetupRoute
  '/theming': typeof ThemingRoute
  '/base-ui/accordion': typeof BaseUiAccordionRoute
  '/base-ui/aspect-ratio': typeof BaseUiAspectRatioRoute
  '/base-ui/avatar': typeof BaseUiAvatarRoute
  '/base-ui/badge': typeof BaseUiBadgeRoute
  '/base-ui/banner': typeof BaseUiBannerRoute
  '/base-ui/button': typeof BaseUiButtonRoute
  '/base-ui/button-group': typeof BaseUiButtonGroupRoute
  '/base-ui/chart': typeof BaseUiChartRoute
  '/base-ui/checkbox': typeof BaseUiCheckboxRoute
  '/base-ui/collapsible': typeof BaseUiCollapsibleRoute
  '/base-ui/dialog': typeof BaseUiDialogRoute
  '/base-ui/drawer': typeof BaseUiDrawerRoute
  '/base-ui/dropdown-menu': typeof BaseUiDropdownMenuRoute
  '/base-ui/field': typeof BaseUiFieldRoute
  '/base-ui/file-upload': typeof BaseUiFileUploadRoute
  '/base-ui/form-section': typeof BaseUiFormSectionRoute
  '/base-ui/input': typeof BaseUiInputRoute
  '/base-ui/input-group': typeof BaseUiInputGroupRoute
  '/base-ui/kbd': typeof BaseUiKbdRoute
  '/base-ui/label': typeof BaseUiLabelRoute
  '/base-ui/pagination': typeof BaseUiPaginationRoute
  '/base-ui/progress': typeof BaseUiProgressRoute
  '/base-ui/radio-group': typeof BaseUiRadioGroupRoute
  '/base-ui/skeleton': typeof BaseUiSkeletonRoute
  '/base-ui/slider': typeof BaseUiSliderRoute
  '/base-ui/spinner': typeof BaseUiSpinnerRoute
  '/base-ui/switch': typeof BaseUiSwitchRoute
  '/base-ui/tabs': typeof BaseUiTabsRoute
  '/base-ui/textarea': typeof BaseUiTextareaRoute
  '/base-ui/toast': typeof BaseUiToastRoute
  '/base-ui/tooltip': typeof BaseUiTooltipRoute
  '/components/app-layout': typeof ComponentsAppLayoutRoute
  '/components/choice-card': typeof ComponentsChoiceCardRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/confirmation-modal': typeof ComponentsConfirmationModalRoute
  '/components/copy-button': typeof ComponentsCopyButtonRoute
  '/components/customer-card': typeof ComponentsCustomerCardRoute
  '/components/data-list': typeof ComponentsDataListRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/detail-card': typeof ComponentsDetailCardRoute
  '/components/empty': typeof ComponentsEmptyRoute
  '/components/form-builder': typeof ComponentsFormBuilderRoute
  '/components/form-layout': typeof ComponentsFormLayoutRoute
  '/components/metric-card': typeof ComponentsMetricCardRoute
  '/components/page-layout': typeof ComponentsPageLayoutRoute
  '/components/quantity-input': typeof ComponentsQuantityInputRoute
  '/components/resource-picker': typeof ComponentsResourcePickerRoute
  '/components/role-select': typeof ComponentsRoleSelectRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/staff-select': typeof ComponentsStaffSelectRoute
  '/components/text-editor': typeof ComponentsTextEditorRoute
  '/base-ui/': typeof BaseUiIndexRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components-json'
    | '/installation'
    | '/setup'
    | '/theming'
    | '/base-ui/accordion'
    | '/base-ui/aspect-ratio'
    | '/base-ui/avatar'
    | '/base-ui/badge'
    | '/base-ui/banner'
    | '/base-ui/button'
    | '/base-ui/button-group'
    | '/base-ui/chart'
    | '/base-ui/checkbox'
    | '/base-ui/collapsible'
    | '/base-ui/dialog'
    | '/base-ui/drawer'
    | '/base-ui/dropdown-menu'
    | '/base-ui/field'
    | '/base-ui/file-upload'
    | '/base-ui/form-section'
    | '/base-ui/input'
    | '/base-ui/input-group'
    | '/base-ui/kbd'
    | '/base-ui/label'
    | '/base-ui/pagination'
    | '/base-ui/progress'
    | '/base-ui/radio-group'
    | '/base-ui/skeleton'
    | '/base-ui/slider'
    | '/base-ui/spinner'
    | '/base-ui/switch'
    | '/base-ui/tabs'
    | '/base-ui/textarea'
    | '/base-ui/toast'
    | '/base-ui/tooltip'
    | '/components/app-layout'
    | '/components/choice-card'
    | '/components/command'
    | '/components/confirmation-modal'
    | '/components/copy-button'
    | '/components/customer-card'
    | '/components/data-list'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/detail-card'
    | '/components/empty'
    | '/components/form-builder'
    | '/components/form-layout'
    | '/components/metric-card'
    | '/components/page-layout'
    | '/components/quantity-input'
    | '/components/resource-picker'
    | '/components/role-select'
    | '/components/select'
    | '/components/sidebar'
    | '/components/staff-select'
    | '/components/text-editor'
    | '/base-ui/'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components-json'
    | '/installation'
    | '/setup'
    | '/theming'
    | '/base-ui/accordion'
    | '/base-ui/aspect-ratio'
    | '/base-ui/avatar'
    | '/base-ui/badge'
    | '/base-ui/banner'
    | '/base-ui/button'
    | '/base-ui/button-group'
    | '/base-ui/chart'
    | '/base-ui/checkbox'
    | '/base-ui/collapsible'
    | '/base-ui/dialog'
    | '/base-ui/drawer'
    | '/base-ui/dropdown-menu'
    | '/base-ui/field'
    | '/base-ui/file-upload'
    | '/base-ui/form-section'
    | '/base-ui/input'
    | '/base-ui/input-group'
    | '/base-ui/kbd'
    | '/base-ui/label'
    | '/base-ui/pagination'
    | '/base-ui/progress'
    | '/base-ui/radio-group'
    | '/base-ui/skeleton'
    | '/base-ui/slider'
    | '/base-ui/spinner'
    | '/base-ui/switch'
    | '/base-ui/tabs'
    | '/base-ui/textarea'
    | '/base-ui/toast'
    | '/base-ui/tooltip'
    | '/components/app-layout'
    | '/components/choice-card'
    | '/components/command'
    | '/components/confirmation-modal'
    | '/components/copy-button'
    | '/components/customer-card'
    | '/components/data-list'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/detail-card'
    | '/components/empty'
    | '/components/form-builder'
    | '/components/form-layout'
    | '/components/metric-card'
    | '/components/page-layout'
    | '/components/quantity-input'
    | '/components/resource-picker'
    | '/components/role-select'
    | '/components/select'
    | '/components/sidebar'
    | '/components/staff-select'
    | '/components/text-editor'
    | '/base-ui'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/components-json'
    | '/installation'
    | '/setup'
    | '/theming'
    | '/base-ui/accordion'
    | '/base-ui/aspect-ratio'
    | '/base-ui/avatar'
    | '/base-ui/badge'
    | '/base-ui/banner'
    | '/base-ui/button'
    | '/base-ui/button-group'
    | '/base-ui/chart'
    | '/base-ui/checkbox'
    | '/base-ui/collapsible'
    | '/base-ui/dialog'
    | '/base-ui/drawer'
    | '/base-ui/dropdown-menu'
    | '/base-ui/field'
    | '/base-ui/file-upload'
    | '/base-ui/form-section'
    | '/base-ui/input'
    | '/base-ui/input-group'
    | '/base-ui/kbd'
    | '/base-ui/label'
    | '/base-ui/pagination'
    | '/base-ui/progress'
    | '/base-ui/radio-group'
    | '/base-ui/skeleton'
    | '/base-ui/slider'
    | '/base-ui/spinner'
    | '/base-ui/switch'
    | '/base-ui/tabs'
    | '/base-ui/textarea'
    | '/base-ui/toast'
    | '/base-ui/tooltip'
    | '/components/app-layout'
    | '/components/choice-card'
    | '/components/command'
    | '/components/confirmation-modal'
    | '/components/copy-button'
    | '/components/customer-card'
    | '/components/data-list'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/detail-card'
    | '/components/empty'
    | '/components/form-builder'
    | '/components/form-layout'
    | '/components/metric-card'
    | '/components/page-layout'
    | '/components/quantity-input'
    | '/components/resource-picker'
    | '/components/role-select'
    | '/components/select'
    | '/components/sidebar'
    | '/components/staff-select'
    | '/components/text-editor'
    | '/base-ui/'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsJsonRoute: typeof ComponentsJsonRoute
  InstallationRoute: typeof InstallationRoute
  SetupRoute: typeof SetupRoute
  ThemingRoute: typeof ThemingRoute
  BaseUiAccordionRoute: typeof BaseUiAccordionRoute
  BaseUiAspectRatioRoute: typeof BaseUiAspectRatioRoute
  BaseUiAvatarRoute: typeof BaseUiAvatarRoute
  BaseUiBadgeRoute: typeof BaseUiBadgeRoute
  BaseUiBannerRoute: typeof BaseUiBannerRoute
  BaseUiButtonRoute: typeof BaseUiButtonRoute
  BaseUiButtonGroupRoute: typeof BaseUiButtonGroupRoute
  BaseUiChartRoute: typeof BaseUiChartRoute
  BaseUiCheckboxRoute: typeof BaseUiCheckboxRoute
  BaseUiCollapsibleRoute: typeof BaseUiCollapsibleRoute
  BaseUiDialogRoute: typeof BaseUiDialogRoute
  BaseUiDrawerRoute: typeof BaseUiDrawerRoute
  BaseUiDropdownMenuRoute: typeof BaseUiDropdownMenuRoute
  BaseUiFieldRoute: typeof BaseUiFieldRoute
  BaseUiFileUploadRoute: typeof BaseUiFileUploadRoute
  BaseUiFormSectionRoute: typeof BaseUiFormSectionRoute
  BaseUiInputRoute: typeof BaseUiInputRoute
  BaseUiInputGroupRoute: typeof BaseUiInputGroupRoute
  BaseUiKbdRoute: typeof BaseUiKbdRoute
  BaseUiLabelRoute: typeof BaseUiLabelRoute
  BaseUiPaginationRoute: typeof BaseUiPaginationRoute
  BaseUiProgressRoute: typeof BaseUiProgressRoute
  BaseUiRadioGroupRoute: typeof BaseUiRadioGroupRoute
  BaseUiSkeletonRoute: typeof BaseUiSkeletonRoute
  BaseUiSliderRoute: typeof BaseUiSliderRoute
  BaseUiSpinnerRoute: typeof BaseUiSpinnerRoute
  BaseUiSwitchRoute: typeof BaseUiSwitchRoute
  BaseUiTabsRoute: typeof BaseUiTabsRoute
  BaseUiTextareaRoute: typeof BaseUiTextareaRoute
  BaseUiToastRoute: typeof BaseUiToastRoute
  BaseUiTooltipRoute: typeof BaseUiTooltipRoute
  ComponentsAppLayoutRoute: typeof ComponentsAppLayoutRoute
  ComponentsChoiceCardRoute: typeof ComponentsChoiceCardRoute
  ComponentsCommandRoute: typeof ComponentsCommandRoute
  ComponentsConfirmationModalRoute: typeof ComponentsConfirmationModalRoute
  ComponentsCopyButtonRoute: typeof ComponentsCopyButtonRoute
  ComponentsCustomerCardRoute: typeof ComponentsCustomerCardRoute
  ComponentsDataListRoute: typeof ComponentsDataListRoute
  ComponentsDataTableRoute: typeof ComponentsDataTableRoute
  ComponentsDatePickerRoute: typeof ComponentsDatePickerRoute
  ComponentsDetailCardRoute: typeof ComponentsDetailCardRoute
  ComponentsEmptyRoute: typeof ComponentsEmptyRoute
  ComponentsFormBuilderRoute: typeof ComponentsFormBuilderRoute
  ComponentsFormLayoutRoute: typeof ComponentsFormLayoutRoute
  ComponentsMetricCardRoute: typeof ComponentsMetricCardRoute
  ComponentsPageLayoutRoute: typeof ComponentsPageLayoutRoute
  ComponentsQuantityInputRoute: typeof ComponentsQuantityInputRoute
  ComponentsResourcePickerRoute: typeof ComponentsResourcePickerRoute
  ComponentsRoleSelectRoute: typeof ComponentsRoleSelectRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSidebarRoute: typeof ComponentsSidebarRoute
  ComponentsStaffSelectRoute: typeof ComponentsStaffSelectRoute
  ComponentsTextEditorRoute: typeof ComponentsTextEditorRoute
  BaseUiIndexRoute: typeof BaseUiIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components-json': {
      id: '/components-json'
      path: '/components-json'
      fullPath: '/components-json'
      preLoaderRoute: typeof ComponentsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theming': {
      id: '/theming'
      path: '/theming'
      fullPath: '/theming'
      preLoaderRoute: typeof ThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/': {
      id: '/base-ui/'
      path: '/base-ui'
      fullPath: '/base-ui/'
      preLoaderRoute: typeof BaseUiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/accordion': {
      id: '/base-ui/accordion'
      path: '/base-ui/accordion'
      fullPath: '/base-ui/accordion'
      preLoaderRoute: typeof BaseUiAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/aspect-ratio': {
      id: '/base-ui/aspect-ratio'
      path: '/base-ui/aspect-ratio'
      fullPath: '/base-ui/aspect-ratio'
      preLoaderRoute: typeof BaseUiAspectRatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/avatar': {
      id: '/base-ui/avatar'
      path: '/base-ui/avatar'
      fullPath: '/base-ui/avatar'
      preLoaderRoute: typeof BaseUiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/badge': {
      id: '/base-ui/badge'
      path: '/base-ui/badge'
      fullPath: '/base-ui/badge'
      preLoaderRoute: typeof BaseUiBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/banner': {
      id: '/base-ui/banner'
      path: '/base-ui/banner'
      fullPath: '/base-ui/banner'
      preLoaderRoute: typeof BaseUiBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/button': {
      id: '/base-ui/button'
      path: '/base-ui/button'
      fullPath: '/base-ui/button'
      preLoaderRoute: typeof BaseUiButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/button-group': {
      id: '/base-ui/button-group'
      path: '/base-ui/button-group'
      fullPath: '/base-ui/button-group'
      preLoaderRoute: typeof BaseUiButtonGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/chart': {
      id: '/base-ui/chart'
      path: '/base-ui/chart'
      fullPath: '/base-ui/chart'
      preLoaderRoute: typeof BaseUiChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/checkbox': {
      id: '/base-ui/checkbox'
      path: '/base-ui/checkbox'
      fullPath: '/base-ui/checkbox'
      preLoaderRoute: typeof BaseUiCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/collapsible': {
      id: '/base-ui/collapsible'
      path: '/base-ui/collapsible'
      fullPath: '/base-ui/collapsible'
      preLoaderRoute: typeof BaseUiCollapsibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/dialog': {
      id: '/base-ui/dialog'
      path: '/base-ui/dialog'
      fullPath: '/base-ui/dialog'
      preLoaderRoute: typeof BaseUiDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/drawer': {
      id: '/base-ui/drawer'
      path: '/base-ui/drawer'
      fullPath: '/base-ui/drawer'
      preLoaderRoute: typeof BaseUiDrawerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/dropdown-menu': {
      id: '/base-ui/dropdown-menu'
      path: '/base-ui/dropdown-menu'
      fullPath: '/base-ui/dropdown-menu'
      preLoaderRoute: typeof BaseUiDropdownMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/field': {
      id: '/base-ui/field'
      path: '/base-ui/field'
      fullPath: '/base-ui/field'
      preLoaderRoute: typeof BaseUiFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/file-upload': {
      id: '/base-ui/file-upload'
      path: '/base-ui/file-upload'
      fullPath: '/base-ui/file-upload'
      preLoaderRoute: typeof BaseUiFileUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/form-section': {
      id: '/base-ui/form-section'
      path: '/base-ui/form-section'
      fullPath: '/base-ui/form-section'
      preLoaderRoute: typeof BaseUiFormSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/input': {
      id: '/base-ui/input'
      path: '/base-ui/input'
      fullPath: '/base-ui/input'
      preLoaderRoute: typeof BaseUiInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/input-group': {
      id: '/base-ui/input-group'
      path: '/base-ui/input-group'
      fullPath: '/base-ui/input-group'
      preLoaderRoute: typeof BaseUiInputGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/kbd': {
      id: '/base-ui/kbd'
      path: '/base-ui/kbd'
      fullPath: '/base-ui/kbd'
      preLoaderRoute: typeof BaseUiKbdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/label': {
      id: '/base-ui/label'
      path: '/base-ui/label'
      fullPath: '/base-ui/label'
      preLoaderRoute: typeof BaseUiLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/pagination': {
      id: '/base-ui/pagination'
      path: '/base-ui/pagination'
      fullPath: '/base-ui/pagination'
      preLoaderRoute: typeof BaseUiPaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/progress': {
      id: '/base-ui/progress'
      path: '/base-ui/progress'
      fullPath: '/base-ui/progress'
      preLoaderRoute: typeof BaseUiProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/radio-group': {
      id: '/base-ui/radio-group'
      path: '/base-ui/radio-group'
      fullPath: '/base-ui/radio-group'
      preLoaderRoute: typeof BaseUiRadioGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/skeleton': {
      id: '/base-ui/skeleton'
      path: '/base-ui/skeleton'
      fullPath: '/base-ui/skeleton'
      preLoaderRoute: typeof BaseUiSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/slider': {
      id: '/base-ui/slider'
      path: '/base-ui/slider'
      fullPath: '/base-ui/slider'
      preLoaderRoute: typeof BaseUiSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/spinner': {
      id: '/base-ui/spinner'
      path: '/base-ui/spinner'
      fullPath: '/base-ui/spinner'
      preLoaderRoute: typeof BaseUiSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/switch': {
      id: '/base-ui/switch'
      path: '/base-ui/switch'
      fullPath: '/base-ui/switch'
      preLoaderRoute: typeof BaseUiSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/tabs': {
      id: '/base-ui/tabs'
      path: '/base-ui/tabs'
      fullPath: '/base-ui/tabs'
      preLoaderRoute: typeof BaseUiTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/textarea': {
      id: '/base-ui/textarea'
      path: '/base-ui/textarea'
      fullPath: '/base-ui/textarea'
      preLoaderRoute: typeof BaseUiTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/toast': {
      id: '/base-ui/toast'
      path: '/base-ui/toast'
      fullPath: '/base-ui/toast'
      preLoaderRoute: typeof BaseUiToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base-ui/tooltip': {
      id: '/base-ui/tooltip'
      path: '/base-ui/tooltip'
      fullPath: '/base-ui/tooltip'
      preLoaderRoute: typeof BaseUiTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/app-layout': {
      id: '/components/app-layout'
      path: '/components/app-layout'
      fullPath: '/components/app-layout'
      preLoaderRoute: typeof ComponentsAppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/choice-card': {
      id: '/components/choice-card'
      path: '/components/choice-card'
      fullPath: '/components/choice-card'
      preLoaderRoute: typeof ComponentsChoiceCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/command': {
      id: '/components/command'
      path: '/components/command'
      fullPath: '/components/command'
      preLoaderRoute: typeof ComponentsCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/confirmation-modal': {
      id: '/components/confirmation-modal'
      path: '/components/confirmation-modal'
      fullPath: '/components/confirmation-modal'
      preLoaderRoute: typeof ComponentsConfirmationModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/copy-button': {
      id: '/components/copy-button'
      path: '/components/copy-button'
      fullPath: '/components/copy-button'
      preLoaderRoute: typeof ComponentsCopyButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/customer-card': {
      id: '/components/customer-card'
      path: '/components/customer-card'
      fullPath: '/components/customer-card'
      preLoaderRoute: typeof ComponentsCustomerCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-list': {
      id: '/components/data-list'
      path: '/components/data-list'
      fullPath: '/components/data-list'
      preLoaderRoute: typeof ComponentsDataListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-table': {
      id: '/components/data-table'
      path: '/components/data-table'
      fullPath: '/components/data-table'
      preLoaderRoute: typeof ComponentsDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/date-picker': {
      id: '/components/date-picker'
      path: '/components/date-picker'
      fullPath: '/components/date-picker'
      preLoaderRoute: typeof ComponentsDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/detail-card': {
      id: '/components/detail-card'
      path: '/components/detail-card'
      fullPath: '/components/detail-card'
      preLoaderRoute: typeof ComponentsDetailCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/empty': {
      id: '/components/empty'
      path: '/components/empty'
      fullPath: '/components/empty'
      preLoaderRoute: typeof ComponentsEmptyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/form-builder': {
      id: '/components/form-builder'
      path: '/components/form-builder'
      fullPath: '/components/form-builder'
      preLoaderRoute: typeof ComponentsFormBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/form-layout': {
      id: '/components/form-layout'
      path: '/components/form-layout'
      fullPath: '/components/form-layout'
      preLoaderRoute: typeof ComponentsFormLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/metric-card': {
      id: '/components/metric-card'
      path: '/components/metric-card'
      fullPath: '/components/metric-card'
      preLoaderRoute: typeof ComponentsMetricCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/page-layout': {
      id: '/components/page-layout'
      path: '/components/page-layout'
      fullPath: '/components/page-layout'
      preLoaderRoute: typeof ComponentsPageLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/quantity-input': {
      id: '/components/quantity-input'
      path: '/components/quantity-input'
      fullPath: '/components/quantity-input'
      preLoaderRoute: typeof ComponentsQuantityInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/resource-picker': {
      id: '/components/resource-picker'
      path: '/components/resource-picker'
      fullPath: '/components/resource-picker'
      preLoaderRoute: typeof ComponentsResourcePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/role-select': {
      id: '/components/role-select'
      path: '/components/role-select'
      fullPath: '/components/role-select'
      preLoaderRoute: typeof ComponentsRoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sidebar': {
      id: '/components/sidebar'
      path: '/components/sidebar'
      fullPath: '/components/sidebar'
      preLoaderRoute: typeof ComponentsSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/staff-select': {
      id: '/components/staff-select'
      path: '/components/staff-select'
      fullPath: '/components/staff-select'
      preLoaderRoute: typeof ComponentsStaffSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/text-editor': {
      id: '/components/text-editor'
      path: '/components/text-editor'
      fullPath: '/components/text-editor'
      preLoaderRoute: typeof ComponentsTextEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsJsonRoute: ComponentsJsonRoute,
  InstallationRoute: InstallationRoute,
  SetupRoute: SetupRoute,
  ThemingRoute: ThemingRoute,
  BaseUiAccordionRoute: BaseUiAccordionRoute,
  BaseUiAspectRatioRoute: BaseUiAspectRatioRoute,
  BaseUiAvatarRoute: BaseUiAvatarRoute,
  BaseUiBadgeRoute: BaseUiBadgeRoute,
  BaseUiBannerRoute: BaseUiBannerRoute,
  BaseUiButtonRoute: BaseUiButtonRoute,
  BaseUiButtonGroupRoute: BaseUiButtonGroupRoute,
  BaseUiChartRoute: BaseUiChartRoute,
  BaseUiCheckboxRoute: BaseUiCheckboxRoute,
  BaseUiCollapsibleRoute: BaseUiCollapsibleRoute,
  BaseUiDialogRoute: BaseUiDialogRoute,
  BaseUiDrawerRoute: BaseUiDrawerRoute,
  BaseUiDropdownMenuRoute: BaseUiDropdownMenuRoute,
  BaseUiFieldRoute: BaseUiFieldRoute,
  BaseUiFileUploadRoute: BaseUiFileUploadRoute,
  BaseUiFormSectionRoute: BaseUiFormSectionRoute,
  BaseUiInputRoute: BaseUiInputRoute,
  BaseUiInputGroupRoute: BaseUiInputGroupRoute,
  BaseUiKbdRoute: BaseUiKbdRoute,
  BaseUiLabelRoute: BaseUiLabelRoute,
  BaseUiPaginationRoute: BaseUiPaginationRoute,
  BaseUiProgressRoute: BaseUiProgressRoute,
  BaseUiRadioGroupRoute: BaseUiRadioGroupRoute,
  BaseUiSkeletonRoute: BaseUiSkeletonRoute,
  BaseUiSliderRoute: BaseUiSliderRoute,
  BaseUiSpinnerRoute: BaseUiSpinnerRoute,
  BaseUiSwitchRoute: BaseUiSwitchRoute,
  BaseUiTabsRoute: BaseUiTabsRoute,
  BaseUiTextareaRoute: BaseUiTextareaRoute,
  BaseUiToastRoute: BaseUiToastRoute,
  BaseUiTooltipRoute: BaseUiTooltipRoute,
  ComponentsAppLayoutRoute: ComponentsAppLayoutRoute,
  ComponentsChoiceCardRoute: ComponentsChoiceCardRoute,
  ComponentsCommandRoute: ComponentsCommandRoute,
  ComponentsConfirmationModalRoute: ComponentsConfirmationModalRoute,
  ComponentsCopyButtonRoute: ComponentsCopyButtonRoute,
  ComponentsCustomerCardRoute: ComponentsCustomerCardRoute,
  ComponentsDataListRoute: ComponentsDataListRoute,
  ComponentsDataTableRoute: ComponentsDataTableRoute,
  ComponentsDatePickerRoute: ComponentsDatePickerRoute,
  ComponentsDetailCardRoute: ComponentsDetailCardRoute,
  ComponentsEmptyRoute: ComponentsEmptyRoute,
  ComponentsFormBuilderRoute: ComponentsFormBuilderRoute,
  ComponentsFormLayoutRoute: ComponentsFormLayoutRoute,
  ComponentsMetricCardRoute: ComponentsMetricCardRoute,
  ComponentsPageLayoutRoute: ComponentsPageLayoutRoute,
  ComponentsQuantityInputRoute: ComponentsQuantityInputRoute,
  ComponentsResourcePickerRoute: ComponentsResourcePickerRoute,
  ComponentsRoleSelectRoute: ComponentsRoleSelectRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSidebarRoute: ComponentsSidebarRoute,
  ComponentsStaffSelectRoute: ComponentsStaffSelectRoute,
  ComponentsTextEditorRoute: ComponentsTextEditorRoute,
  BaseUiIndexRoute: BaseUiIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
